apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencypt.org/directory
    email: 'not.my.email@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
        ingress:
          class: nginx